export const constant = {
  ADMIN: "Admin",
  CUSTOMER: "Customer",
  VENDOR: "Vendor",
  SIGNUP: "Sign Up",
  LOGIN: "Log in",
  EMAIL: "Email",
  PASSWORD: "Password",
  NEW_PASSWORD: "New Password",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  MOBILE_NO: "Mobile No",
  DOB: "DOB",
  SUBMIT: "Submit",
  BACK: "Back",
  EDIT: "Edit",
  UPDATE: "Update",
  ADD: "Add",
  VIEW_BOOK: "View Books",
  BOOK_TITLE: "Book Title",
  BOOK_AUTHOR: "Book Author",
  PUBLISHER_NAME: "Publisher Name",
  PUBLISHER_YEAR: "Publish Year",
  RENT: "Rent",
  ACTIONS: "Actions",
  CART: "Cart",
  PAY: "Pay",
};
